version: '3.8'

services:
  my-db:
    image: postgres:15
    container_name: my-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"

  api-service:
    build: .                
    container_name: api-service
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=my-db        
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - my-db               